services:
  - type: web
    name: keeptrack
    runtime: static
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://keeptrack-api.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
